# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(choices=[(None, '선택해주세요'), (0, '~ 19'), (1, '20 ~ 29'), (2, '30 ~ 39'), (3, '40 ~ 49'), (4, '50 ~ 59'), (5, '60 ~ 69'), (6, '70 ~')], verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.IntegerField(choices=[(None, '선택해주세요'), (0, '없음'), (1, '초등(국민)학교'), (2, '중학교'), (3, '고등학교'), (4, '전문대학 (2, 3년제)'), (5, '대학교 (4년제)'), (6, '대학원 (석사과정)'), (7, '대학원 (박사과정)')], verbose_name='최종 학력'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(None, '선택해주세요'), (0, '남성'), (1, '여성'), (2, '그 외')], verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.IntegerField(choices=[(None, '선택해주세요'), (0, '0 ~ 199 만원'), (1, '200 ~ 449 만원'), (2, '450 ~ 699 만원'), (3, '700 ~ 949 만원'), (4, '950 ~ 만원')], verbose_name='월소득'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.IntegerField(choices=[(None, '선택해주세요'), (0, '관리전문직'), (1, '준전문사무직'), (2, '학생'), (3, '서비스판매직'), (4, '생산기능노무직'), (5, '주부'), (6, '무직 및 기타')], verbose_name='현재 직업'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='political_affinity',
            field=models.IntegerField(choices=[(None, '선택해주세요'), (0, '매우 진보적'), (1, '다소 진보적'), (2, '중도적'), (3, '다소 보수적'), (4, '매우 보수적')], verbose_name='정치 성향'),
        ),
    ]
