# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20171115_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.IntegerField(choices=[(None, '선택해주세요'), (0, '관리 (공공·기업, 행정·경영지원, 전문서비스, 건설·전기, 판매·고객서비스)'), (1, '전문 (과학, 공학, 보건·사회복지, 교육, 법률, 경영.금융, 문화·예술·스포츠)'), (2, '사무 (경영·회계, 금융·보험, 법률·감사, 상담·안내·통계)'), (3, '서비스 (경찰·소방·보안, 미용·예식·의료보조, 운송·여가, 조리·음식)'), (4, '판매 (영업, 매장 판매, 방문·노점·통신)'), (5, '농립어업 (농축산, 임업, 어업)'), (6, '기능원 (식품가공, 섬유·의복·가죽, 목재·가구·악기·간판, 금속성형, 운송·기계, 전기·전자, 건설·채굴, 영상·통신)'), (7, '기계조작 (식품가공, 섬유·신발, 화학, 금속·비금속, 기계제조, 전기·전자, 운전·운송, 상하수도·재활용, 목재·인쇄)'), (8, '단순노무 (건설·광업, 운송, 제조, 청소·경비, 가사·음식, 농림어업)'), (9, '학생'), (10, '주부'), (11, '군인'), (12, '무직 및 기타')], verbose_name='현재 직업'),
        ),
    ]
