# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_userprofile_marriage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
