# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20171211_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='children',
            field=models.IntegerField(choices=[(None, '선택해주세요'), (0, '자녀가 있다'), (1, '자녀가 없다')], default=0, verbose_name='자녀 유무'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dependent',
            field=models.IntegerField(choices=[(None, '선택해주세요'), (0, '부양할 어르신이 있다'), (0, '부양할 어르신이 없다')], default=0, verbose_name='부양 의무'),
            preserve_default=False,
        ),
    ]
