# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20171211_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dependent',
            field=models.IntegerField(choices=[(None, '선택해주세요'), (0, '부양할 어르신이 있다'), (1, '부양할 어르신이 없다')], verbose_name='부양 의무'),
        ),
    ]
