# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_userpostprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostprofile',
            name='q1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, help_text='세금을 내는 이상, 모든 공약의 실현에는 비용이 든다.<br/>                   따라서 나에게 이득이 되지 않은 공약은 나에게 손해다', verbose_name='설문 1'),
        ),
        migrations.AlterField(
            model_name='userpostprofile',
            name='q2',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, help_text='나의 가족의 손해는 나의 손해다', verbose_name='설문 2'),
        ),
        migrations.AlterField(
            model_name='userpostprofile',
            name='q3',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, help_text='우리 사회의 손해는 나의 손해다', verbose_name='설문 3'),
        ),
        migrations.AlterField(
            model_name='userpostprofile',
            name='q4',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, help_text='자연의 손해는 나의 손해다', verbose_name='설문 4'),
        ),
    ]
