# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0002_candidate_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='pid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
