# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0003_promise_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='help_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
