# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0004_election_help_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='game_step',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
