# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0005_election_game_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promise',
            name='pid',
        ),
    ]
