# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0007_promise_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='ko_name',
            field=models.CharField(default='파일럿 선거', max_length=20),
            preserve_default=False,
        ),
    ]
