# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0009_auto_20171123_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile',
            field=models.CharField(max_length=200),
        ),
    ]
