# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0010_auto_20171207_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='color_class',
            field=models.CharField(default='grey', max_length=20),
            preserve_default=False,
        ),
    ]
